version: '3'
services:
  laravel:
    build: ./docker/build
    container_name: laravel
    restart: unless-stopped
    privileged: true
    ports:
      - 80:80
      - "22:22"
    volumes:
      - ./:/var/www/html
      - ./docker/settings:/settings
      - ./docker/temp:/backup
      - composer_cache:/root/.composer/cache
    environment:
      - ENABLE_XDEBUG=true
  mysql:
    image: mariadb:10.2
    container_name: mysql
    volumes:
      - ./docker/db_config:/etc/mysql/conf.d
      - ./docker/db_files:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel

volumes:
  db:
  storage:
  composer_cache: